---
# dunst: Simple and configurable notification-daemon

- name: install/upgrade dunst
  package:
    state: latest
    name: dunst

- name: create dunst user config directories
  file:
    state: directory
    path: "{{ user_home_dir }}/.config/dunst"
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: 0750
    setype: config_home_t
    seuser: system_u

- name: push dunstrc config
  copy:
    src: dunstrc
    dest: "{{ user_home_dir }}/.config/dunst/dunstrc"
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: 0640
    setype: config_home_t
    seuser: system_u
