---
- name: install/upgrade EPEL and IUS repositories
  package:
    state: latest
    name:
      - epel-release
      - https://rhel7.iuscommunity.org/ius-release.rpm

- name: install base packages
  package:
    state: present
    name:
      - bash-completion
      - firewalld
      - git
      - golang
      - htop
      - jq
      - pandoc
      - podman
      - python-flake8
      - python36u
      - python36u-pip
      - rpmconf
      - smartmontools
      - strace
      - which

- name: install/upgrade Python pipenv package
  become_user: "{{ target_user }}"
  pip:
    executable: pip3.6
    state: latest
    extra_args: "--user"
    name: pipenv
