---
os: linux
dist: bionic

jobs:
  include:

    - language: python
      python: 3.8
      cache: pip
      install:
        - pipenv lock --dev --requirements > /tmp/requirements.txt
        - pip install -r /tmp/requirements.txt
      script:
        - yamllint -c .yamllint .
        - ansible-lint -x 305,401,403 playbooks/centos-server.yml
        - ansible-lint -x 305,401,403 playbooks/fedora-workstation.yml
        - ansible-lint -x 305,401,403 playbooks/rhel-workstation.yml

    - language: ruby
      rvm:
        - 2.6.5
      cache:
        bundler: true
        directories:
          - $TRAVIS_BUILD_DIR/tmp/.htmlproofer
      script:
        - bundle exec sh gen_docs.sh
        - bundle exec rake test
      deploy:
        local_dir: "docs/_build"
        provider: pages
        skip_cleanup: true
        target_branch: gh-pages
        token: "$GITHUB_TOKEN"
        on:
          branch: master

notifications:
  irc:
    channels:
      - "ircs://chat.freenode.net:6697/##jwf"
    template:
      - "[%{repository_name}:%{branch}@%{commit} - build #%{build_number}] CI %{result}! (%{build_url})"
    on_success: change
    on_failure: always

env:
  global:
    - secure: IsasRPaE7SDnQIAFKfOhUetOhpIKODXDO6ejVZnksckadiQnwP4Y5ohzLwkKLa/je3wA1omhk0ZrEZ87yMFU8xejVURjLf0qf6qC/ABJ4DjdAnhScSQKY4mjXtBVhnbpRLxW7eYIhmcdqYMVn4PsuG3hU7AdiVX7nWCmR31r5FK+8NfyvxhFtycX20aY7QWVFKi8coMU7ucJSnKTqglldOrgYbrHqhFxSnmZUpq9LEgo+9cS3KDdAwFdtOMtyURv99jlb+gMzDm9H+CZuRUfq1BytkOM/Rsojnb0vf+ZnVH4xSAGw9//OoxSosGsiulaaCViI1nWUT0Gl91Qa43HBKD9j8QJrt/OrtGnfz3+1utCg8IAenFsKBtEqcIjLJ4BjBZLJMMZ8Qm2yqrcPTXCdCAgEmFkIS174zAPuOz3weXc/bkqG5IiB6ucrapyKNbxQ1j6rw+4QOSLkVj7qXYozMj8tywRQ6ZebSeV8yH8ial13t0mVBFQGVVXafweCk4Mn8VsdR1Ke/e1Yg7oonPFaTM/ecB5LEG7rqdAOcKfIPpGSRkKk3CjFJJhjAbf96uysiLx2aTyNVvjR1oIV7INM70DSWBxiIakiWBAG9eMLrBccFPFw7poGeZN7ewljV8rdGrVR8jvDYR0CzY4XkFWjXRmcvpc4SOVJNyHHVM8hYI=
