---
- name: install bugwarrior
  package:
    state: latest
    name: bugwarrior

- name: create bugwarrior user config directory
  file:
    state: directory
    path: "{{ user_home_dir }}/.config/bugwarrior"
    group: "{{ target_user }}"
    owner: "{{ target_user }}"

- name: add bugwarriorrc
  copy:
    src: "{{ role_path }}/files/bugwarriorrc"
    dest: "{{ user_home_dir }}/.config/bugwarrior/bugwarriorrc"
    group: "{{ target_user }}"
    owner: "{{ target_user }}"
