---
- name: install/upgrade thunderbird
  package:
    state: latest
    name:
      - thunderbird
      - thunderbird-enigmail

- name: add mail filters for primary email account (desktop path)
  when: ansible_hostname == "ff"
  copy:
    src: "{{ role_path }}/files/msgFilterRules.dat"
    dest: "{{ user_home_dir }}/.thunderbird/cq8izn4c.default/ImapMail/imap.googlemail.com/msgFilterRules.dat"
    group: "{{ target_user }}"
    owner: "{{ target_user }}"
    mode: 0660

- name: add mail filters for primary email account (laptop path)
  when: ansible_hostname == "fossbook"
  copy:
    src: "{{ role_path }}/files/msgFilterRules.dat"
    dest: "{{ user_home_dir }}/.thunderbird/cl5szv8k.default/ImapMail/imap.googlemail.com/msgFilterRules.dat"
    group: "{{ target_user }}"
    owner: "{{ target_user }}"
    mode: 0660
