---
- name: import global variables
  include_vars:
    dir: "{{ inventory_dir }}/group_vars/"

- name: remove unused packages
  package:
    state: absent
    name:
      - cmus
      - evolution
      - evolution-ews
      - evolution-help
      - gnome-boxes
      - gnome-calendar
      - gnome-characters
      - gnome-classic-session
      - gnome-contacts
      - gnome-documents
      - gnome-documents-libs
      - gnome-getting-started-docs
      - gnome-initial-setup
      - gnome-maps
      - gnome-photos
      - gnome-shell-extension-pomodoro
      - gnome-system-monitor
      - gnome-weather
      - logwatch
      - mediawriter
      - mosh
      - origin-clients
      - powerline
      - ntp
      - task
      - tmux-powerline
      - tomahawk

- name: add target user
  user:
    name: "{{ target_user }}"
    group: "{{ target_group }}"
    comment: "{{ target_user_name }}"
    groups: wheel
    append: yes
    generate_ssh_key: yes
    ssh_key_file: ".ssh/id_ed25519"
    ssh_key_type: ed25519

- name: create misc. workspace directories
  file:
    state: directory
    path: "{{ user_home_dir }}/{{ item }}"
    group: "{{ target_group }}"
    owner: "{{ target_user }}"
    seuser: system_u
  loop:
    - .ansible/tmp
    - git
    - wkspc

- name: purge unused files
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ user_home_dir }}/.bash_completion.d/"
    - "{{ user_home_dir }}/.taskrc"
    - "/etc/bash_completion.d/task.bash-completion"

- name: clone dotfile repository from GitHub
  become: yes
  become_user: "{{ target_user }}"
  git:
    repo: "git@github.com:jwflory/swiss-army.git"
    dest: "{{ user_home_dir }}/git/swiss-army"
    update: no
    version: HEAD

- name: install custom /etc/hosts file from someonewhocares.org
  get_url:
    url: https://someonewhocares.org/hosts/zero/hosts
    dest: /etc/hosts
    force: yes
    mode: 0644
    setype: net_conf_t
    seuser: system_u
