---
- name: install taskwarrior
  package:
    state: present
    name: task

- name: add taskrc
  template:
    src: "{{ role_path }}/files/taskrc"
    dest: "{{ user_home_dir }}/.taskrc"
    group: "{{ target_user }}"
    owner: "{{ target_user }}"
