---
- name: configure dnf to keep two versions of kernel installed at once
  lineinfile:
    dest: /etc/dnf/dnf.conf
    regexp: '^installonly_limit='
    line: 'installonly_limit=2'

# gids/uids required for podman rootless mode
# https://github.com/jwflory/swiss-army/issues/11
- name: set multiple gids for target user
  lineinfile:
    path: "/etc/subgid"
    regexp: "^{{ target_user }}:"
    line: "{{ target_user }}:10000:65536"
    seuser: system_u

- name: set multiple uids for target user
  lineinfile:
    path: "/etc/subuid"
    regexp: "^{{ target_user }}:"
    line: "{{ target_user }}:10000:65536"
    seuser: system_u
