---
- name: import third-party repository signing keys
  rpm_key: key={{ item }} state=present
  loop:
    - https://negativo17.org/repos/RPM-GPG-KEY-slaanesh

- name: add/upgrade RPM Fusion repositories
  package:
    state: latest
    name:
      - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version }}.noarch.rpm
      - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_version }}.noarch.rpm

- name: add other third-party repositories
  get_url:
    dest: "/etc/yum.repos.d/"
    url: "{{ item }}"
    setype: system_conf_t
    seuser: system_u
  loop:
    - https://negativo17.org/repos/fedora-flash-plugin.repo
    - https://negativo17.org/repos/fedora-spotify.repo

- name: install base packages
  ### Package notes ###
  # Fedora packaging tools: fedora-packager, fedpkg, copr-cli
  # chromaprint-tools: Capture digital fingerprints of audio files
  # cmus: ncurses-based music player
  # exfat-utils: FS formatting tools (exFAT)
  # f2fs-tools: FS formatting tools (Flash-Friendly File System)
  # gstreamer1-plugins-bad-nonfree: MPEG2 codec support
  # jpegoptim: Utility to optimize JPEG files
  # meld: Visual diff and merge tool
  # network-manager-applet: Network control / status applet for NetworkManager
  # remmina: Remote Desktop client
  # poppler-utils: Command line utilities for converting PDF files
  # udftools: FS formatting tools (Universal Disk Format)
  package:
    state: present
    name:
      - https://dl.google.com/linux/direct/google-musicmanager-beta_current_x86_64.rpm
      - ansible
      - arandr
      - bash-completion
      - black
      - blueman
      - bpftrace
      - brasero
      - brasero-nautilus
      - buildah
      - chromaprint-tools
      - chromium
      - cmus
      - docker-compose
      - duply
      - epiphany
      - exfat-utils
      - f2fs-tools
      - feh
      - ffmpeg
      - firewalld
      - flash-plugin
      - fpaste
      - git
      - gnome-mahjongg
      - gobby05
      - golang
      - google-roboto-slab-fonts
      - gstreamer-ffmpeg
      - gstreamer1-plugins-bad-free-extras
      - gstreamer1-plugins-ugly
      - hexchat
      - htop
      - inkscape
      - java-11-openjdk
      - jpegoptim
      - jq
      - libvirt
      - libvirt-devel
      - meld
      - moby-engine
      - mpris-scrobbler
      - mpv
      - nautilus-dropbox
      - network-manager-applet
      - nodejs-yarn
      - overpass-fonts
      - overpass-mono-fonts
      - pandoc
      - pass
      - pavucontrol
      - picard
      - planner
      - podman
      - poppler-utils
      - powerline-fonts
      - pulseaudio-utils
      - remmina
      - rpmconf
      - smartmontools
      - spotify-client
      - strace
      - telegram-desktop
      - typetype-molot-fonts
      - udftools
      - '@vagrant'
      - vagrant-doc
      - vagrant-sshfs
      - '@virtualization'
      - visualboyadvance-m
      - wireshark
      - yamllint
      - youtube-dl
