---
- name: start/enable docker
  service:
    name: docker
    state: started
    enabled: yes
  # On Fedora 31 or later, Docker is broken with CgroupsV2.
  # https://fedoraproject.org/wiki/Changes/CGroupsV2
  ignore_errors: yes

- name: start/enable firewalld
  service:
    name: firewalld
    state: started
    enabled: yes

#
# Need upstream bug fixed with i3wm before systemd service file will work
# correctly. See https://github.com/i3/i3/issues/3565 for more info.
#
# - name: get type of system install (desktop|laptop)
#   command: "cat {{ user_home_dir }}/.jwf-identifier"
#   register: system_type
#
# - name: add jwf-fix-desktop-monitor-on-boot.service
#   when: system_type.stdout == "desktop"
#   template:
#     src: jwf-fix-desktop-monitor-on-boot.service
#     dest: "/usr/lib/systemd/system/jwf-fix-desktop-monitor-on-boot.service"
#     mode: 0644
#     seuser: system_u
#     setype: systemd_unit_file_t
#
# - name: start/enable jwf-fix-desktop-monitor-on-boot
#   when: system_type.stdout == "desktop"
#   service:
#     name: jwf-fix-desktop-monitor-on-boot
#     state: started
#     enabled: yes
