---
- name: add new groups - docker, libvirt
  group: name={{ item }}
  with_items:
    - docker
    - libvirt

- name: add target user to new groups
  user:
    name: "{{ target_user }}"
    groups: docker,libvirt
    append: yes
