---
- name: install ruby and other build dependencies
  # gdbm-devel: Contains libraries/headers required for some rubygems
  package:
    state: present
    name:
      - ruby
      - ruby-devel
      - rubygems
      - gdbm-devel

- name: add gemrc
  template:
    src: gemrc
    dest: "{{ user_home_dir }}/.gemrc"
    mode: 0644
    setype: user_home_t
    seuser: system_u
