---
- name: set permissions on system bash_completion.d directory
  file:
    state: directory
    path: "/etc/bash_completion.d"
    mode: 0755
    serole: object_r
    setype: etc_t
    seuser: system_u

- name: copy bashrc and bash_profile
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ user_home_dir }}/.{{ item }}"
    group: "{{ target_user }}"
    owner: "{{ target_user }}"
    mode: 0444
    seuser: system_u
  loop:
    - bashrc
    - bash_profile

- name: copy user Bash auto-completion scripts to system directory
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "/etc/bash_completion.d/{{ item }}"
    mode: 0644
    serole: object_r
    setype: etc_t
    seuser: system_u
  loop:
    - poetry.bash-completion
    - task.bash-completion
