---
- name: synchronize Lucie's preferred RHEL 8 Workstation
  hosts: 192.168.1.2
  become: yes

  vars:
    target_group: jwf
    target_user: jwf
    user_home_dir: /home/jwf

  roles:
    - { role: system/base, tags: ['base', 'system'] }
    - { role: system/rhel-workstation/8, tags: ['rhel', 'system'] }
    - { role: apps/bash, tags: ['bash', 'terminal', 'apps'] }
    - { role: apps/git, tags: ['git', 'terminal', 'apps'] }
    - { role: apps/powerline-go, tags: ['powerline', 'terminal', 'apps'] }
    - { role: apps/ssh, tags: ['ssh', 'terminal', 'apps'] }
    - { role: apps/sublime-text, tags: ['sublime-text', 'desktop', 'apps'] }
    - { role: apps/vim, tags: ['vim', 'terminal', 'apps'] }
